version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - /mnt/data/mysql/data:/var/lib/mysql

    networks:
      - config-store-net
      - spending-tracker-net

networks:
  config-store-net:
    external: true
  spending-tracker-net:
    external: true
